all:
  children:
    leader:
      hosts:
        arthur:
    manager:
      hosts:
        arthur:          
    worker:
      hosts:
        galahad:
    minetest:
      hosts:
        galahad:
    jenkins:
      hosts:
        galahad:
