all:
  children:
    leader:
      hosts:
        arthur:
    manager:
      hosts:
        arthur:          
    worker:
      hosts:
        galahad:
    data:
      hosts:
        arthur: 
        galahad:
    minetest:
      hosts:
        galahad:
