- hosts: all
  roles:
    - system
    - docker
- hosts: leader
  roles:
    - swarm-leader
- hosts: manager
  roles:
    - swarm-manager
- hosts: worker
  roles:
    - swarm-worker
    - gluster
- hosts: leader
  roles:
    - swarm-tools