- import_playbook: system.yml
- import_playbook: docker.yml
- import_playbook: swarm-leader.yml
- import_playbook: swarm-manager.yml
- import_playbook: swarm-worker.yml
- import_playbook: gluster.yml
