---
# tasks file for swarm-tools

- name: 'Downloading Docker Swarm Visualizer docker image'
  become: true
  docker_image:
    name: alexellis2/visualizer-arm:latest
    source: pull 
    
- name: 'Deploying Docker Swarm Visualizer'
  become: true
  docker_swarm_service:
    name: viz
    image: alexellis2/visualizer-arm:latest
    publish:
      - published_port: 8080
        target_port: 8080
    placement:
      constraints:
        - node.role == manager
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
