- name: Create data directory
  file:
    path: "{{ directory.gluster }}"
    state: directory
    mode: '0777'

- name: Create volume directory
  file:
    path: "{{ directory.volume.shared }}"
    state: directory
    mode: '0777'