- name: 'Attach peer'
  become: true
  gluster_peer:
    state: present
    nodes: "{{ groups['worker'] | map('extract', hostvars, ['ansible_host']) | join(',')  }}"
  when: "groups['worker']|length > 1"
         
- name: 'Create gluster volume rebalanced'
  become: true
  gluster_volume:
    state: present
    name: gvolume
    bricks: "{{ directory.gluster }}"
    rebalance: yes
    cluster: "{{ groups['worker'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
    force: true
  when: "groups['worker']|length > 1"
  run_once: true

- name: 'Create gluster volume not rebalanced'
  become: true
  gluster_volume:
    state: present
    name: gvolume
    bricks: "{{ directory.gluster }}"
    rebalance: no
    cluster: "{{ groups['worker'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
    force: true
  when: "groups['worker']|length == 1"
  run_once: true

- name: 'Start gluster volume'
  become: true
  gluster_volume:
    state: started
    name: gvolume

- name: 'Get volume state'
  shell: "mount | grep gvolume | cat"
  args:
    warn: false
  register: mounted
  changed_when: false

- name: 'Mount volume'
  become: true
  shell: "mount -t glusterfs localhost:/gvolume '{{ directory.volume.shared }}'"
  args:
    warn: false  
  when: "mounted.stdout_lines|length <= 0"