---
# defaults file for docker
packages:
  - apt-transport-https 
  - ca-certificates 
  - software-properties-common
  - python3-pip
  - libffi-dev
  - libssl-dev

packages_python:
  - docker
  - docker-compose