- name: 'Adding jenkins=true label to jenkins node'
  docker_node:
    hostname: "{{ hostvars[item]['inventory_hostname']  }}"
    labels:
      jenkins: "true"
    labels_state: merge
  loop: "{{groups['jenkins']}}"

- name: 'Create working directory'
  tempfile:
    state: directory
    suffix: temp_jenkins
  register: temp_dir

- name: "Copy Dockerfile"    
  become: true
  copy:
    src: 'Dockerfile'
    dest: '{{ temp_dir.path }}'

- name: "Copy docker-compose file"    
  become: true
  vars:
    leader: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}"
    volume_jenkins: "{{ directory.volume }}"
    volume_maven: "{{ directory.maven }}"
  template:
    src: 'docker-compose.yml'
    dest: '{{ temp_dir.path }}'

- name: "Build image"
  docker_compose:
    project_src: "{{ temp_dir.path }}"
    build: yes
    
- name: "Tag and push to registry"
  docker_image:
    name: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}:9001/jenkins"
    repository: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}:9001/jenkins"
    push: yes
    source: local

- name: Deploy stack
  docker_stack:
    state: present
    name: jenkins
    compose:
      - "{{ temp_dir.path }}/docker-compose.yml"

- name: 'Cleaning temps directory'
  become: true
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  when: temp_dir.path is defined
