- name: 'Prepare Volume Home'
  file:
    path: '{{ directory.volume }}/home'
    state: directory
    mode: '0755'  

- name: 'Prepare Volume Logs'
  file:
    path: '{{ directory.volume }}/logs'
    state: directory
    mode: '0755'  

- name: 'Prepare Maven volumes'
  file:
    path: '{{ directory.maven }}'
    state: directory
    mode: '0755'  