---
# tasks file for minetest
- name: 'Minetest'
  docker_swarm_service:
    name: minetest
    image: linuxserver/minetest
    publish:
      - published_port: 30000
        target_port: 30000
        protocol: udp
    placement:
      constraints:
        - node.role == worker
    mounts:
      - source: /home/pi/volumes/minetest
        target: /config/.minetest
        type: bind