- name: 'Collecting installed mods'
  find:
    paths: '{{ directory.volume }}/mods'
    recurse: false
    file_type: directory
  register: installed_mods_file

- name: 'Initializing installed mod list'
  set_fact:
    imods: []

- name: 'Extracting installed mods name'
  set_fact: 
    imods: "{{ imods|default([]) + [item['path'] | basename] }}"
  loop: "{{ installed_mods_file.files }}"
  loop_control:
    label: "{{ item['path'] }}"

- name: 'Initializing mods to install list'
  set_fact:
    nmods: []

- name: 'Filtering mods to install'
  set_fact: 
    nmods: "{{ nmods|default([]) + [item] }}"
  when: item.name not in imods
  loop: "{{ mods }}"
  loop_control:
    label: "{{ item.name }}"  

- name: 'Prepare Volumes'
  file:
    path: '{{ directory.volume }}'
    state: directory
    mode: '0755'  

- name: 'Create Minetest mods directory'
  file:
    path: '{{ directory.volume }}/mods'
    state: directory
    mode: '0755'  

- name: 'Create Minetest world directory'
  file:
    path: '{{ directory.volume }}/worlds/world'
    state: directory
    mode: '0755'  

- name: 'Create working directory'
  tempfile:
    state: directory
    suffix: temp_minetest
  when: "nmods|length > 0" 
  register: temp_dir

- name: Download mods
  get_url:
    url: '{{ item.url }}'
    dest: '{{ temp_dir.path }}/{{ item.name }}.zip'
    mode: '0440'
  when: "nmods|length > 0" 
  loop: "{{ nmods }}"
  loop_control:
    label: "{{ item.name }}"   

- name: 'Extract mods'
  unarchive:
    src: '{{ temp_dir.path }}/{{ item.name }}.zip'
    dest: '{{ temp_dir.path }}'
    remote_src: yes
  when: "nmods|length > 0" 
  loop: "{{ nmods }}"
  loop_control:
    label: "{{ item.name }}"   

- name: 'copy mods to minetest directory'
  become: true
  copy:
    src: '{{ temp_dir.path }}/{{ item.name }}'
    dest: '{{ directory.volume }}/mods'
    remote_src: yes
  when: "nmods|length > 0" 
  loop: "{{ nmods }}"
  loop_control:
    label: "{{ item.name }}"   

- name: 'copy world.mt to minetest directory'
  become: true
  copy:
    src: 'world.mt'
    dest: '{{ directory.volume }}/worlds/world'
  when: "nmods|length > 0" 

- name: 'Cleaning temps directory'
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  when: temp_dir.path is defined

- name: "Activating mods"  
  become: true
  lineinfile:
    dest: '{{ directory.volume }}/worlds/world/world.mt'
    line: 'load_mod_{{ item.name }} = true'  
  when: "nmods|length > 0" 
  loop: "{{ nmods }}"
  loop_control:
    label: "{{ item.name }}"   

- name: 'Cleaning working directory'
  file:
    path: '{{ directory.work }}'
    state: absent  