- name: 'Create working directory'
  tempfile:
    state: directory
    suffix: temp_murmur
  register: temp_dir

- name: "Copy Dockerfile"    
  become: true
  copy:
    src: 'Dockerfile'
    dest: '{{ temp_dir.path }}'

- name: "Copy docker-compose file"    
  become: true
  vars:
    leader: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}"
    volume: "{{ directory.volume }}"
  template:
    src: 'docker-compose.yml'
    dest: '{{ temp_dir.path }}'

- name: "Build image"
  docker_compose:
    project_src: "{{ temp_dir.path }}"
    build: yes
    
- name: "Tag and push to registry"
  docker_image:
    name: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}:5000/murmur"
    repository: "{{ hostvars[groups['leader'][0]]['inventory_hostname'] }}:5000/murmur"
    push: yes
    source: local

- name: Deploy stack
  docker_stack:
    state: present
    name: murmur
    compose:
      - "{{ temp_dir.path }}/docker-compose.yml"

# docker image push image-tag
# docker stack deploy --compose-file docker-compose.yml murmur

#- name: 'Cleaning temps directory'
#  become: true
#  file:
#    path: "{{ temp_dir.path }}"
#    state: absent
#  when: temp_dir.path is defined
