---
# Updating hostname
- name: "Updating /etc/hostname"
  become: true
  hostname:
    name: '{{ hostname.short }}'

- name: "Updating /etc/hosts"  
  become: true
  lineinfile:
     dest: /etc/hosts
     line: '127.0.1.1       {{ hostname.short }}'    

- name: Reboot the server and wait for it to come back up.
  become: true
  reboot: