---
# tasks file for minetest
- name: 'Prepare minetest volume'
  import_tasks: minetest_prepare.yml
  when: "'minetest' in group_names"

- name: 'Install minetest service'
  import_tasks: minetest_install.yml
  when: "'leader' in group_names"
